#include "ArkanoidConstants.h"


StrId ARK_ACTION_LEFT("ARK_ACTION_LEFT");
StrId ARK_ACTION_RIGHT("ARK_ACTION_RIGHT");
StrId ARK_ACTION_RELEASE("ARK_ACTION_RELEASE");

StrId ARK_EVENT_GAME_STARTED("ARK_EVENT_GAME_STARTED");
StrId ARK_EVENT_LEVEL_STARTED("ARK_EVENT_LEVEL_STARTED");
StrId ARK_EVENT_ROUND_STARTED("ARK_EVENT_ROUND_STARTED");
StrId ARK_EVENT_OBJECT_HIT("ARK_EVENT_OBJECT_HIT");
StrId ARK_EVENT_BALL_OUTSIDE_AREA("ARK_EVENT_BALL_OUTSIDE_AREA");
StrId ARK_EVENT_GAME_OVER("ARK_EVENT_GAME_OVER");
StrId ARK_EVENT_LEVEL_COMPLETED("ARK_EVENT_LEVEL_COMPLETED");
StrId ARK_EVENT_GAME_COMPLETED("ARK_EVENT_GAME_COMPLETED");
StrId ARK_EVENT_LIFE_LOST("ARK_EVENT_LIFE_LOST");

StrId ARK_COMMAND_FINISH_LEVEL("ARK_COMMAND_FINISH_LEVEL");

char ARKANOID_MODEL[] = "ARKANOID_MODEL";
char ATTR_MOVEMENT_STR[] = "ATTR_MOVEMENT";