#include "Constants.h"

namespace Cog {

	StrId ACT_BEHAVIOR_ADDED("ACT_BEHAVIOR_ADDED");
	StrId ACT_BEHAVIOR_REMOVED("ACT_BEHAVIOR_REMOVED");
	StrId ACT_OBJECT_CREATED("ACT_OBJECT_CREATED");
	StrId ACT_OBJECT_REMOVED("ACT_OBJECT_REMOVED");
	StrId ACT_USER_INPUT("ACT_USER_INPUT");
	StrId ACT_COLLISION_OCURRED("ACT_COLLISION_OCURRED");
	StrId ACT_NODE_DESTROYED("ACT_NODE_DESTROYED");
	StrId ACT_ATTRIBUTE_CHANGED("ACT_ATTRIBUTE_CHANGED");
	StrId ACT_OBJECT_HIT_STARTED("ACT_OBJECT_HIT_STARTED");
	StrId ACT_OBJECT_HIT_OVER("ACT_OBJECT_HIT_OVER");
	StrId ACT_OBJECT_HIT_LOST("ACT_OBJECT_HIT_LOST");
	StrId ACT_OBJECT_HIT_ENDED("ACT_OBJECT_HIT_ENDED");
	StrId ACT_APP_FINISHED("ACT_APP_FINISHED");
	StrId ACT_TWEEN_ENDED("ACT_TWEEN_ENDED");
	StrId ACT_DELAY_ACTION("ACT_DELAY_ACTION");
	StrId ACT_SCENE_SWITCHED("ACT_SCENE_SWITCHED");
	StrId ACT_PROCESS_ENDED("ACT_PROCESS_ENDED");
	StrId ACT_BEHAVIOR_FINISHED("ACT_BEHAVIOR_FINISHED");
	StrId ACT_STATE_CHANGED("ACT_STATE_CHANGED");
	StrId ACT_TRANSFORM_ENDED("ACT_TRANSFORM_ENDED");
	StrId ACT_KEY_PRESSED("ACT_KEY_PRESSED");
	StrId ACT_MOUSE_SCROLLED("ACT_MOUSE_SCROLLED");
	StrId ACT_SCREEN_CHANGED("ACT_SCREEN_CHANGED");
	StrId ACT_NET_MESSAGE_RECEIVED("ACT_NET_MESSAGE_RECEIVED");
	StrId ACT_NET_CONNECTED("ACT_NET_CONNECTED");
	StrId ACT_NET_DISCONNECTED("ACT_NET_DISCONNECTED");
	StrId ACT_NET_CONNECTION_LOST("ACT_NET_CONNECTION_LOST");
	StrId ACT_NET_CALLBACK_RECEIVED("ACT_NET_CALLBACK_RECEIVED");
	StrId ACT_UPDATE_MESSAGE_RECEIVED("ACT_UPDATE_MESSAGE_RECEIVED");
	StrId ACT_OBJECT_SELECTED("ACT_OBJECT_SELECTED");
	StrId ACT_BUTTON_CLICKED("ACT_BUTTON_CLICKED");
	StrId ACT_ATTR_CHANGED("ACT_ATTR_CHANGED");

	/** Attribute keys */
	StrId ATTR_MOVEMENT("ATTR_MOVEMENT");
	StrId ATTR_STEERING_BEH_DEST("ATTR_STEERING_BEH_DEST");
	StrId ATTR_STEERING_BEH_WANDER("ATTR_STEERING_BEH_WANDER");
	StrId ATTR_ACTIONS("ATTR_ACTIONS");
	StrId ATTR_ALLOWED_ACTIONS("ATTR_ALLOWED_ACTIONS");
	StrId ATTR_BOUNDS("ATTR_BOUNDS");
	StrId ATTR_SIZE("ATTR_SIZE");
	StrId ATTR_POLYGON("ATTR_POLYGON");
	StrId ATTR_FRAME("ATTR_FRAME");
	StrId ATTR_COLLISIONS("ATTR_COLLISIONS");
	StrId ATTR_IMGBOUNDS("ATTR_IMGBOUNDS");
	StrId ATTR_SLIDER_VALUE("ATTR_SLIDER_VALUE");

	/** States*/
	StrId STATE_HITTABLE("STATE_HITTABLE");
	StrId STATE_TOLEFT("STATE_TOLEFT");
	StrId STATE_TORIGHT("STATE_TORIGHT");
	StrId STATE_HIT("STATE_HIT");
	StrId STATE_COLLID_SOURCE("STATE_COLLID_SOURCE");
	StrId STATE_COLLID_TARGET("STATE_COLLID_TARGET");
	StrId STATE_DISABLED("STATE_DISABLED");
	StrId STATE_ENABLED("STATE_ENABLED");
	StrId STATE_LOCKED("STATE_LOCKED");
	StrId STATE_SELECTED("STATE_SELECTED");

	/** Net messages */
	StrId NET_MSG_UPDATE("NET_MSG_UPDATE");


}// namespace