#include "GameValues.h"
// hashed strings initialization

StrId COPTER_CREATED("COPTER_CREATED");
StrId UNIT_LANDED("UNIT_LANDED");
StrId PROJECTILE_SHOT("PROJECTILE_SHOT");
StrId UNIT_KILLED("UNIT_KILLED");
StrId ANIMATION_ENDED("ANIMATION_ENDED");
StrId GAME_OVER("GAME_OVER");
StrId PARATROOPER_CREATED("PARATROOPER_CREATED");

StrId MODEL("MODEL");
StrId COLLISION("COLLISION");
StrId PARA_STATE("PARA_STATE");

StrId ACTION_LEFT("ACTION_LEFT");
StrId ACTION_RIGHT("ACTION_RIGHT");
StrId ACTION_FIRE("ACTION_FIRE");
